### ISSUE TITLE
3D Output Initilization Error with DXVK Selected

### ISSUE THREAD

**Issue by magnapeccatrix** [megai2/SelectRenderer#1]
Hello, I would like to try [DXVK](https://github.com/doitsujin/dxvk) but I get this error probably because I don't have a DXVK dll or don't know where to put it to make SelectRenderer to use it. 

Working when selected D3D9 or D912PXY renderer with no errors. 

![image](https://user-images.githubusercontent.com/15203877/117585380-d1ad6580-b11a-11eb-8945-542ebb2cf12a.png)

![image](https://user-images.githubusercontent.com/15203877/117585387-de31be00-b11a-11eb-841f-65555aec0d32.png)

**Comment by magnapeccatrix** [comment]
Update:

I tried something and it actually worked.

I made a new folder called 'DXVK' and put the DXVK dll inside of it, this seems to solve the problem.

![image](https://user-images.githubusercontent.com/15203877/117585610-079f1980-b11c-11eb-8bc6-4b77cb6f1d35.png)


![image](https://user-images.githubusercontent.com/15203877/117585571-de7e8900-b11b-11eb-9b42-144a49582161.png)

**Comment by megai2** [comment]
Hi. Added info in readme + updated release to include latest changes about options availability and load status
