### ISSUE TITLE
Selection for DX11 not working

### ISSUE THREAD

**Issue by J0s3f** [megai2/SelectRenderer#7]
I have dxvk and dxvk-async installed. For dx9, I can select them in the UI (also d912pxy). For dx11, there are the radio buttons infront of dxvk and dxvk-async, so they are detected, but when I click them, the selected button stays on stock

https://user-images.githubusercontent.com/604089/143965320-1f3843b0-2879-4c48-90eb-2c011d9e161a.mp4

.

**Comment by megai2** [comment]
Fixed in 1.4.2

**Comment by J0s3f** [comment]
Perfect, that fixed it!
